services:
    neo4j:
        image: neo4j:5
        container_name: neo4j
        restart: unless-stopped
        ports:
            - '7474:7474'
            - '7687:7687'
        environment:
            - NEO4J_AUTH=neo4j/neo4j_password
            - NEO4J_PLUGINS=["apoc"]
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*
        volumes:
            - ./neo4j/data:/data
            - ./neo4j/logs:/logs
            - ./neo4j/plugins:/plugins

    qdrant:
        image: qdrant/qdrant:latest
        container_name: qdrant
        restart: unless-stopped
        ports:
            - '6333:6333'
            - '6334:6334'
        volumes:
            - ./qdrant/storage:/qdrant/storage

    redis:
        image: redis:7-alpine
        command:
            ['redis-server', '--appendonly', 'yes', '--appendfsync', 'everysec']
        volumes:
            - redis:/data
        ports:
            - '6379:6379'

    minio:
        image: minio/minio:latest
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: 'minio'
            MINIO_ROOT_PASSWORD: 'minio12345'
            MINIO_BROWSER_REDIRECT_URL: 'http://localhost:9001'
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - minio:/data
        healthcheck:
            test:
                ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            interval: 5s
            timeout: 3s
            retries: 10
        restart: unless-stopped

volumes:
    redis:
    minio:
